// <auto-generated />
using System;
using Bookstore.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bookstore.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bookstore.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nVarChar(50)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "هو طبيب وأديب مصري، ويعتبر من أشهر الكتاب في مجال أدب الرعب وأدب الشباب. ولد في مدينة طنطا عاصمة محافظة الغربية في مصر. متزوج وأب لطفلين هما محمد (12 سنة) ومريم (8 سنوات).\r\nتخرج أحمد خالد توفيق في كلية الطب في جامعة طنطا عام 1985 م وحصل على الدكتوراه في طب المناطق الحارة عام 1997 م. يقدم أحمد خالد توفيق ستة سلاسل للروايات وصلت إلى ما يقرب من 236 عددا، وقد قام بترجمة عدد من الروايات الأجنبية ضمن سلسلة روايات عالمية للجيب. كما قدّم الترجمة العربية الوحيدة لرواية نادي القتال (fight club) للروائي الأمريكي تشاك بولانيك. كما أن له بعض التجارب الشعرية.\r\nوتُوفى إلى رحمة الله تعالى عن عمر يناهز 55 عامًا أثر أزمة صحية ألمت به(عليه رحمة الله تعالى وأسكنه الله فسيح جناته وأبدله سيئاته حسنات إن شاء الله)",
                            ImageURL = "~/images/Authors/أحمد_خالد_توفيق.jpg",
                            Name = "أحمد خالد توفيق"
                        },
                        new
                        {
                            Id = 2,
                            About = " عاش مصطفى محمود في مدينة طنطا إلى جوار مسجد السيد البدوي الذي يعد أحد مزارات الصوفية الشهيرة في مصر مما ترك فيه نفسه أثرا واضحا ظهر في توجهاته وأفكاره ولقد تحدث مصطفى محمود عن تكوينه الفكري وعن طفولته التي هي مفتاح ذلك التكوين قائلا : لا اذكر من طفولتي إلا الأحلام التي كنت أتخيل فيها أنى عالم ومخترع أو رحال أو بطل من إبطال التاريخ كما أذكر حبي للموسيقى وللشعر ، وفى صباي تعلمت العزف على الناي وفى شبابي درست العزف على العود ، وكنت أكتب في أيام الدراسة الابتدائية الزجل والشعر وفى الثانوية القصص والمقالات والمسرحيات وهويت العلوم ، وأنشأت معملا للكيمياء والبيولوجيا في بيتى وكنت أحضر الغازات واشرح الضفادع ، نشرت لي أول قصة في مجلة الرسالة عام 1947 ثم بعد ذلك نشرت القصة الثانية في جريدة المصري ، ثم اشتغلت في أخر ساعة وأخبار اليوم وفى عام 1952 كنت احد مؤسسي مجلة التحرير وفى عام 1956 اشتغلت بمجلة روزاليوسف.\r\n\r\nكانت حياتي الأدبية خلال ثلاثين عاما هجرة مستمرة نحو إدراك الحياة والبحث عن الحقيقة وكان كل كتاب محطة على طريق هذا السفر الطويل.\r\n\r\n",
                            ImageURL = "~/images/Authors/مصطفى محمود.jpg",
                            Name = "مصطفى محمود"
                        },
                        new
                        {
                            Id = 3,
                            About = "إبراهيم السكران (ولد في 5 ربيع الآخر 1396 هـ الموافق 4 أبريل 1976م) باحث ومُفكِّر إسلامي، مهتمٌ بمنهج الفقه الإسلامي وبالمذاهب العقدية والفكرية، له العديد من المؤلفات والأبحاث والمقالات المنشورة وله عدد من الكتب المطبوعة.\r\n\r\nسيرته\r\nهو أبو عُمر، إبراهيم بن عمر بن إبراهيم السكران المشرف الوهبي التميمي، درس في جامعة الملك فهد للبترول والمعادن سنة واحدة، ثم تركها متوجهًا إلى كلية الشريعة في جامعة الإمام محمد بن سعود الإسلامية بالرياض وتخرج منها، نال درجة الماجستير في السياسة الشرعيّة من المعهد العالي للقضاء التابع لجامعة الإمام محمد بن سعود الإسلامية بالرياض، ثم توجه إلى بريطانيا ونال درجة الماجستير في القانون التجاري الدولي في جامعة إسكس بمدينة كولشيستر.\r\n\r\nظهر تحوّل إبراهيم السكران إلى الفكر السلفي عام 1428 هـ 2007 م في ورقة فكريّة انتشرَت وقتها الكترونيًا، عنوانها: مآلات الخِطاب المدني، وقد أثارت هذه الورقة الكثير من المحسوبين على التيار التنويري.  ",
                            ImageURL = "~/images/Authors/إبراهيم السكران.jpeg",
                            Name = "إبراهيم السكران"
                        },
                        new
                        {
                            Id = 4,
                            About = "أحمد مراد أحمد عبسلام (مواليد القاهرة 1978) كاتب ومصور ومصمم جرافيك مصري، تخرّج في مدرسة ليسيه الحرّية بباب اللوق عام 1996 قبل أن يلتحق بالمعهد العالي للسينما ليدرس التصوير السينمائي، وتخرّج عام 2001 بترتيب الأول على القسم، ونالت أفلام تخرّجه \"الهائمون - الثلاث ورقات - وفي اليوم السابع\" جوائز للأفلام القصيرة في مهرجانات بإنجلترا وفرنسا وأوكرانيا.\r\nبدأ مراد كتابة روايته الأولي \"فيرتيجو\" في شتاء عام 2007، ونُشِرت في نفس العام عن دار ميريت قبل أن تُترجم للّغة الإنجليزية عن دار بلومزبيري، ثم للإيطالية عن دار مارسيليو، والفرنسية عن دار فلاماريون، ثم تحولت الرواية لمسلسل تليفزيوني في رمضان من عام 2012 بعنوان فيرتيجو بطولة هند صبري، ونالت الرواية جائزة \"البحر الأبيض المتوسط للثقافة\" لعام 2013 من إيطاليا.\r\nفي فبراير 2010 أصدر مراد روايته الثانية بعنوان \"تراب الماس\" وتُرجمت للإيطالية عن دار مارسيليو وللألمانية، وتم تحويلها لفيلم سينمائي هذا العام 2018.من بطوله اسر ياسين و ماجد الكدوانى.\r\nوفي أكتوبر 2012 صدرت روايته الثالثة \"الفيل الأزرق\" والتي نالت المركز الأول في مبيعات الكتب بمعرض القاهرة الدولي للكتاب 2013، ورشحت الرواية في القائمة القصيرة لجائزة البوكر العربية عام 2014.",
                            ImageURL = "~/images/Authors/احمد مراد.jpg",
                            Name = "أحمد مراد"
                        });
                });

            modelBuilder.Entity("Bookstore.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nVarchar(MAX)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nVarchar(100)");

                    b.Property<int>("NumberOfPages")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nVarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Literature",
                            Description = "لم يكن \"طه\" سوى مندوب دعاية طبية فى شركة أدوية, حياة باهتة رتيبة, بدلة وكرافتة وحقيبة جلدية ولسان لبق يستميل أعتى الأطباء لأدويته.. كان ذلك قبل أن يسقط..\r\nجريمة قتل غامضة تتركه خلفها وقد تبدل عالمه.. للأبد.. تتحول حياته إلى جزيرة من الأسرار, يبدأ اكتشافها فى دفتر عتيق يعثر عليه مصادفة, ويجد أداة رهيبة لها فعل السحر.. سنقرأ هنا كيف تتحول هذه الجريمة إلى سلسلة من عمليات القتل. وكيف يصبح القتل بابا يكشف لنا عالما من الفساد, وسطوة السلطة التى تمتد لأجيال فى تتابع مثير لا يؤكد أبدا أن \"طه\" سيصل إلى نهايته..",
                            ImageURL = "~/Images/Books/تراب الماس.webp",
                            NumberOfPages = 448,
                            Title = "تراب الماس"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Literature",
                            Description = "الرواية فانتازية خيالية تدور أحداثها حول دكتور للأمراض العقلية يدعى - يحيى - كان يعمل في مستشفى العباسية ، كان مدمنا للخمر وتعرض لحادث أدى إلى وفاة زوجته وابنته ، فانعزل عن العالم لمدة خمس سنوات وبعد انقطاع عن العمل عاد مرة أخرى للعمل في نفس المستشفى إلا أنه يتفاجأ بوجود صديق قديم يدعى - شريف - وهو نزيل بالمستشفى كان له ماضي أراد أن ينساه طويلا إلا أنه وقع تحت رحمة يحيى ، فتنقلب حياة يحيى وصديقه راسا على عقب حيث يبدأ يحيى بالتنقيب والبحث عن حقيقة صديقه عبرة رحلة استكشافية مثيرة مليئة بالعالم الغريب والخيالي ليظهر بها الكاتب الخبايا النفسية للبشر وغرائبها .",
                            ImageURL = "~/Images/Books/Al-Feel_al-Azraq.jpg",
                            NumberOfPages = 485,
                            Title = "الفيل الأزرق"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Literature",
                            Description = "سيختطفك أحمد مراد في آلة زمن، ليهبط بك في حقبة تغلي فيها القاهرة بالأحداث.. وثبة زمنية إلى عالم متشابك يمسك المؤلف مقتدرًا بكل مفاتيحه؛ بين سعد زغلول وتعنت البريطانيين، قصة الوفد ومقهى \"متاتيا\" جماعة سرية تعمل تحت مقهى \"ريش\"، وعوالم البغاء المقنن.. شخصيات عديدة سوف تتعاطف معها أو تمقتها، أو تفعل الشيئين بلا تحفظ، بحوار مفعم بالحيوية حتى لتوشك على سماعه يتردد في أذنك، وتفاصيل تاريخية مضنية ودقيقة. سوف تدرك أن البعض ما زال مصرًّا على الجدية والإتقان.",
                            ImageURL = "~/Images/Books/1919.jpeg",
                            NumberOfPages = 485,
                            Title = "1919"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Literature",
                            Description = "قصة فلسطينية مؤلمة تحكي معاناة ثلاثة رجال في طريق هجرتهم إلى الكويت، بحثًا عن الأمل والهروب من الاحتلال، ليواجهوا مصيرًا مفجعًا داخل صهريج شاحنة.",
                            ImageURL = "~/Images/Books/رجال في الشمس.jpg",
                            NumberOfPages = 120,
                            Title = "رجال في الشمس"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Religious",
                            Description = "كتاب فلسفي رائع يروي رحلة مصطفى محمود الفكرية من الإنكار إلى الإيمان، بأسلوب عميق مليء بالتساؤلات والبحث عن الحقيقة.",
                            ImageURL = "~/Images/Books/رحلتي من الشك إلى الإيمان.jpg",
                            NumberOfPages = 160,
                            Title = "رحلتي من الشك إلى الإيمان"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Religious",
                            Description = "رحلة تفسيرية متميزة تركز على الجوانب الفكرية والفلسفية للقرآن الكريم، وتقدم فهمًا عميقًا للآيات بعيدًا عن التقليدية.",
                            ImageURL = "~/Images/Books/رقائق القرآن.webp",
                            NumberOfPages = 300,
                            Title = "رقائق القرآن"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Literature",
                            Description = "حكاية بوليسية شيقة تدور في أروقة البنوك والمؤامرات المالية، حيث تكشف الأحداث عن لعبة ضخمة من الخداع والسرقة في عالم المصارف.",
                            ImageURL = "~/Images/Books/رواية_البنكوت.jpg",
                            NumberOfPages = 410,
                            Title = "رواية البنكوت"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Religious",
                            Description = "من أهم كتب الحديث الشريف، يجمع بين الأخلاق والعبادات في أحاديث نبوية مختارة بعناية لتربية النفس وتزكيتها.",
                            ImageURL = "~/Images/Books/مسلكيات.avif",
                            NumberOfPages = 500,
                            Title = "مسلكيات"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Religious",
                            Description = "كتاب صوفي عميق للإمام ابن القيم، يشرح فيه منازل السائرين إلى الله في طريق العبودية، بلغة قوية وعقيدة سليمة.",
                            ImageURL = "~/Images/Books/مدارج السالكين.jpg",
                            NumberOfPages = 600,
                            Title = "مدارج السالكين"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Literature",
                            Description = "مجموعة قصصية مشوقة تدور أحداثها داخل غرفة غامضة تحمل أسرارًا لا تنتهي، حيث يصبح الدخول إليها تجربة تغير حياة كل من يقترب منها.",
                            ImageURL = "~/Images/Books/حكايات الغرفة 207.webp",
                            NumberOfPages = 200,
                            Title = "حكايات الغرفة 207"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Literature",
                            Description = "رحلة فكرية مرعبة في دهاليز العقل والروح، تجمع بين التشويق والخيال العلمي، بأسلوب فلسفي عميق يلامس النفس الإنسانية.",
                            ImageURL = "~/Images/Books/عقل بلا جسد.webp",
                            NumberOfPages = 190,
                            Title = "عقل بلا جسد"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Literature",
                            Description = "مجموعة من القصص القصيرة التي تستعرض مواقف إنسانية في ظلال الليل، حيث تتجلى مشاعر الوحدة والخوف والحنين.",
                            ImageURL = "~/Images/Books/رفقاء الليل.webp",
                            NumberOfPages = 240,
                            Title = "رفقاء الليل"
                        },
                        new
                        {
                            Id = 13,
                            Category = "History",
                            Description = "كتاب تاريخي يقدم عرضًا مبسطًا وممتعًا لحياة المصريين القدماء، وعاداتهم، وعلومهم، وأسلوب حياتهم اليومي.",
                            ImageURL = "~/Images/Books/في ممر القديمة.webp",
                            NumberOfPages = 310,
                            Title = "في ممر القديمة"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Literature",
                            Description = "رواية سوداوية عن مستقبل مرعب، تتخيل انقسام المجتمع المصري إلى طبقتين: الأغنياء في الجنة والطبقة المسحوقة في الجحيم، في إطار درامي فلسفي.",
                            ImageURL = "~/Images/Books/يوتوبيا.webp",
                            NumberOfPages = 172,
                            Title = "يوتوبيا"
                        });
                });

            modelBuilder.Entity("Bookstore.Models.BookAuthor", b =>
                {
                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.HasKey("AuthorId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("BookAuthors");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            BookId = 10
                        },
                        new
                        {
                            AuthorId = 1,
                            BookId = 11
                        },
                        new
                        {
                            AuthorId = 1,
                            BookId = 12
                        },
                        new
                        {
                            AuthorId = 1,
                            BookId = 13
                        },
                        new
                        {
                            AuthorId = 1,
                            BookId = 14
                        },
                        new
                        {
                            AuthorId = 2,
                            BookId = 5
                        },
                        new
                        {
                            AuthorId = 2,
                            BookId = 7
                        },
                        new
                        {
                            AuthorId = 3,
                            BookId = 6
                        },
                        new
                        {
                            AuthorId = 3,
                            BookId = 8
                        },
                        new
                        {
                            AuthorId = 3,
                            BookId = 9
                        },
                        new
                        {
                            AuthorId = 4,
                            BookId = 1
                        },
                        new
                        {
                            AuthorId = 4,
                            BookId = 2
                        },
                        new
                        {
                            AuthorId = 4,
                            BookId = 3
                        });
                });

            modelBuilder.Entity("Bookstore.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("nVarChar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Bookstore.Models.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegisterationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Bookstore.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Bookstore.Models.OrderItem", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BookId", "OrderId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Bookstore.Models.BookAuthor", b =>
                {
                    b.HasOne("Bookstore.Models.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookstore.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Bookstore.Models.Comment", b =>
                {
                    b.HasOne("Bookstore.Models.Book", "Book")
                        .WithMany("Comments")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Bookstore.Models.Order", b =>
                {
                    b.HasOne("Bookstore.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Bookstore.Models.OrderItem", b =>
                {
                    b.HasOne("Bookstore.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookstore.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Bookstore.Models.Book", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Bookstore.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
